<?php

namespace Admin\AdminBundle\Repository;

/**
 * Email_placeholderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Email_placeholderRepository extends \Doctrine\ORM\EntityRepository
{
}
