<?php

namespace Admin\AdminBundle\Repository;

/**
 * Status_newsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Status_newsletterRepository extends \Doctrine\ORM\EntityRepository
{
}
