admin_users:
    resource: "@AdminUsersBundle/Resources/config/routing.yml"
    prefix:   /

front_front:
    resource: "@FrontFrontBundle/Resources/config/routing.yml"
    prefix:   /

admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
