email_index:
    path:     /
    defaults: { _controller: "AdminAdminBundle:Email:index" }
    methods:  GET

email_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:Email:show" }
    methods:  GET

email_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:Email:new" }
    methods:  [GET, POST]

email_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:Email:edit" }
    methods:  [GET, POST]

email_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:Email:delete" }
    methods:  DELETE
