pages_index:
    path:     /
    defaults: { _controller: "AdminAdminBundle:Pages:index" }
    methods:  GET

pages_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:Pages:show" }
    methods:  GET

pages_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:Pages:new" }
    methods:  [GET, POST]

pages_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:Pages:edit" }
    methods:  [GET, POST]

pages_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:Pages:delete" }
    methods:  DELETE
